version: '3.7'

services:
<<<<<<< Updated upstream
=======
  
>>>>>>> Stashed changes
  spark-master:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_MASTER_PORT=$SPARK_MASTER_PORT"
      - "SPARK_MASTER_WEBUI_PORT=$SPARK_MASTER_WEBUI_PORT"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/master"
    ports:
      - "$SPARK_MASTER_WEBUI_PORT:$SPARK_MASTER_WEBUI_PORT"
      - "7077:7077"
    volumes:
      - "./app/spark:/app/spark"

  spark-worker-1:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_WORKER_CORES=$SPARK_WORKER_CORES"
      - "SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/worker1"
      - "SPARK_WORKER_DIR=$SPARK_WORKER_DIR/worker1"
    ports:
      - "8081:8081"
    depends_on: 
      - spark-master
    command: worker spark://spark-master:$SPARK_MASTER_PORT
    volumes:
      - "./app/spark:/app/spark"
<<<<<<< Updated upstream
  
  spark-worker-2:
=======

  spark-worker-2:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_WORKER_CORES=$SPARK_WORKER_CORES"
      - "SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY"
      - "SPARK_WORKER_WEBUI_PORT=$SPARK_WORKER_WEBUI_PORT_2"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/worker2"
      - "SPARK_WORKER_DIR=$SPARK_WORKER_DIR/worker2"
    ports:
      - "$SPARK_WORKER_WEBUI_PORT_2:$SPARK_WORKER_WEBUI_PORT_2"
    depends_on: 
      - spark-master
    command: worker spark://spark-master:$SPARK_MASTER_PORT
    volumes:
      - "./app/spark:/app/spark"

  thriftserver:
>>>>>>> Stashed changes
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_WORKER_CORES=$SPARK_WORKER_CORES"
      - "SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/worker2"
      - "SPARK_WORKER_DIR=$SPARK_WORKER_DIR/worker2"
    ports:
      - "8082:8082"
    depends_on: 
<<<<<<< Updated upstream
      - spark-master
    command: worker spark://spark-master:$SPARK_MASTER_PORT
    volumes:
      - "./app/spark:/app/spark"

  zeppelin:
    image: apache/zeppelin:0.9.0
    environment:
      - "SPARK_MASTER=spark://spark-master:$SPARK_MASTER_PORT"
      - "ZEPPELIN_CONF_DIR=$ZEPPELIN_CONF_DIR"
      - "ZEPPELIN_LOG_DIR=$ZEPPELIN_LOG_DIR"
      - "ZEPPELIN_NOTEBOOK_DIR=$ZEPPELIN_NOTEBOOK_DIR"
    ports:
      - "4040:4040"
      - "9080:8080"
    volumes:
      - "./app/zeppelin:/app/zeppelin"

  mysql:
    image: jsminet/docker-mysql-foodmart:latest
    environment: 
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    restart: always
    ports:
        - 7080:8080
=======
      - spark-worker-1
      - spark-worker-2
      - mysql-hive
    command: thriftserver --master spark://$SPARK_MASTER_HOST:$SPARK_MASTER_PORT --verbose
    volumes:
      - "./app/spark:/app/spark"
>>>>>>> Stashed changes
