version: '3.7'

services:
  spark-master:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_MASTER_PORT=$SPARK_MASTER_PORT"
      - "SPARK_MASTER_WEBUI_PORT=$SPARK_MASTER_WEBUI_PORT"
    ports:
      - "$SPARK_MASTER_WEBUI_PORT:$SPARK_MASTER_WEBUI_PORT"

  spark-worker-1:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_WORKER_CORES=$SPARK_WORKER_CORES"
      - "SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY"
    ports:
      - "$SPARK_WORKER_WEBUI_PORT:$SPARK_WORKER_WEBUI_PORT"
    depends_on: 
      - spark-master
    command: worker spark://spark-master:$SPARK_MASTER_PORT

  thriftserver:
    image: ${SPARK_IMAGE}
    networks: 
      - spark
    deploy:
      placement:
        constraints: [node.role == manager]
    environment: 
      - "HIVE_SERVER2_THRIFT_PORT=$HIVE_SERVER2_THRIFT_PORT"
    ports:
      - "$HIVE_SERVER2_THRIFT_PORT:$HIVE_SERVER2_THRIFT_PORT"
    depends_on: 
      - spark-worker
    command: thriftserver --master spark://spark-master:$SPARK_MASTER_PORT --verbose