version: '3.7'

services:

  spark-master:
    image: jsminet/docker-apache-spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    image: jsminet/docker-apache-spark:latest
    ports:
      - "8081:8081"
    command: worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 1
	  SPARK_WORKER_WEBUI_PORT: 8081

  spark-worker-2:
    image: jsminet/docker-apache-spark:latest
    ports:
      - "8082:8082"
    command: worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 1
	  SPARK_WORKER_WEBUI_PORT: 8082

  spark-thriftserver:
    image: jsminet/docker-apache-spark:latest
	ports:
      - "4040:4040"
	  - "10000:10000"
    command: thriftserver --master spark://spark-master:7077