version: '3.7'    

services:

  spark-master:
    image: spark:2.4.4
    ports:
      - "8090:8080"
      - "7077:7077"
  
  spark-worker-1:
    image: spark:2.4.4
    command: worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 1

  spark-worker-2:
    image: spark:2.4.4
    command: worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 1

  spark-worker-3:
    image: spark:2.4.4
    command: worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 1